apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-guide
  template:
    metadata:
      labels:
        app: app-guide
    spec:
      containers:
        - name: reservation-service
          image: reservation
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          env:
          - name: DATABASE_URL
            value: jdbc:mysql://mysql-db:3306/microservices
          - name: DATABASE_USER
            value: root
          - name: DATABASE_PASSWORD
            value: root
