services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3307:3306"
    networks:
      - backend-network
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservices
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    command:
      - --default-authentication-plugin=mysql_native_password

  eureka-server:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    image: eureka
    ports:
      - "8761:8761"
    networks:
      - backend-network

  api-gateway:
    build:
      context: ./api-gateway-service
      dockerfile: Dockerfile
    image: api-gateway
    ports:
      - "8762:8762"
    networks:
      - backend-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

  category-service:
    build:
      context: ./category-service
      dockerfile: Dockerfile
    image: category-service
    ports:
      - "8085:8085"
    networks:
      - backend-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/microservices
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
      - eureka-server

  comments-service:
    build:
      context: ./comments-service
      dockerfile: Dockerfile
    image: comments-service
    ports:
      - "8086:8086"
    networks:
      - backend-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/microservices
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
      - eureka-server

  reservation-service:
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    image: reservation-service
    ports:
      - "8087:8087"
    networks:
      - backend-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/microservices
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql-db
      - eureka-server

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
