apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-guide
  template:
    metadata:
      labels:
        app: app-guide
    spec:
      containers:
        - name: api-gateway-container
          image: api-gate
          imagePullPolicy: Never
          ports:
            - containerPort: 8089



