apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-guide
  template:
    metadata:
      labels:
        app: app-guide
    spec:
      containers:
        - name: descovery-cont
          image: discovery
          imagePullPolicy: Never
          ports:
            - containerPort: 8761